# The name of the relevent project account.
account: EcoGenetics
# Name of species being worked on.
species_name: Stegodyphus bicolor
# Path to sample alignment file (BAM format). Can be a list with multiple entries or a single entry
sample_list:
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_142.1/BIC_142.1_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_150.9/BIC_150.9_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_150.N8/BIC_150.N8_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_262.6/BIC_262.6_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_262.8/BIC_262.8_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/BIC_262.N3/BIC_262.N3_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/S.bic_150.6/S.bic_150.6_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/S.bic_150.20/S.bic_150.20_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/S.bic_262.11/S.bic_262.11_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_bicolor/S.bic_262.N5/S.bic_262.N5_filtered.bam
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_bicolor/BI_hifi_hic_scaffolded_trim.fa
# Path to BED formatted file containing repeat regions
repeat_regions_bed: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_bicolor/annotation/SteBic.repeats.bed
# Directory for intermidiary files and various statistics.
working_directory: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/steps
# What type of sequencing has been used on the samples, individual sequencing or pooled sequencing (individual | pooled)
sequencing_type: individual
# Ploidy of sample. If sample is pooled the value should equal the total number chromosome copies
ploidy: 2
# Freebayes is a haplotype-based variant caller. The value of 'bestn' is the max number of best alternative haplotypes to consider when more are available.
# This is very time and memory intensive (don't use a value higher than 3).
bestn: 3
