# The name of the relevent project account.
account: EcoGenetics
# Name of species being worked on.
species_name: Stegodyphus mimosarum
# Path to sample alignment file (BAM format). Can be a list with multiple entries or a single entry
sample_list:
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f1_1_F/SteMim_f1_1_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f1_6_M/SteMim_f1_6_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f2_2_F/SteMim_f2_2_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f2_7_M/SteMim_f2_7_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f3_3_F/SteMim_f3_3_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f3_8_M/SteMim_f3_8_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f4_4_F/SteMim_f4_4_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f4_8_M/SteMim_f4_8_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_mimosarum/SteMim_f5_7_M/SteMim_f5_7_M_filtered.bam
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_mimosarum/MIM_hifi_hic_scaffolded_trim.fa
# Path to BED formatted file containing repeat regions
repeat_regions_bed: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_mimosarum/annotation/SteMim.repeats.bed
# Directory for intermidiary files and various statistics.
working_directory: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/steps
# What type of sequencing has been used on the samples, individual sequencing or pooled sequencing (individual | pooled)
sequencing_type: individual
# Ploidy of sample. If sample is pooled the value should equal the total number chromosome copies
ploidy: 2
# Freebayes is a haplotype-based variant caller. The value of 'bestn' is the max number of best alternative haplotypes to consider when more are available.
# This is very time and memory intensive (don't use a value higher than 3).
bestn: 3
