# The name of the relevent project account.
account: EcoGenetics
# Name of species being analysed.
species_name: Entomobrya nicoleti
# Path to Hi-C read 1 file.
HiC_read_1_path: /faststorage/project/EcoGenetics/BACKUP/HiC/EntNic/Ent_Nic_L1_1.fq.gz
# Path to Hi-C read 2 file.
HiC_read_2_path: /faststorage/project/EcoGenetics/BACKUP/HiC/EntNic/Ent_Nic_L1_2.fq.gz
# Path to draft genome.
draft_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Entomobrya_nicoleti/EG_EntNic_16022023_genomic_nomask_noann.fna
# Directory for intermidiary files and various statistics.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/steps
