# The name of the relevent project account.
account: EcoGenetics
# Name of species being worked on.
species_name: Stegodyphus sarasinorum
# Path to sample alignment file (BAM format). Can be a list with multiple entries or a single entry
sample_list:
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f1_131_F/SteSar_f1_131_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f1_136_M/SteSar_f1_136_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f2_132_F/SteSar_f2_132_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f2_137_M/SteSar_f2_137_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f3_133_F/SteSar_f3_133_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f3_138_M/SteSar_f3_138_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f4_134_F/SteSar_f4_134_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f4_139_M/SteSar_f4_139_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f5_135_F/SteSar_f5_135_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_sarasinorum/SteSar_f5_140_M/SteSar_f5_140_M_filtered.bam
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_sarasinorum/SARA_hifi_hic_scaffolded_trim.fa
# Path to BED formatted file containing repeat regions
repeat_regions_bed: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_sarasinorum/annotation/SteSar.repeats.bed
# Directory for intermidiary files and various statistics.
working_directory: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/steps
# What type of sequencing has been used on the samples, individual sequencing or pooled sequencing (individual | pooled)
sequencing_type: individual
# Ploidy of sample. If sample is pooled the value should equal the total number chromosome copies
ploidy: 2
# Freebayes is a haplotype-based variant caller. The value of 'bestn' is the max number of best alternative haplotypes to consider when more are available.
# This is very time and memory intensive (don't use a value higher than 3).
bestn: 3
