# The name of the relevent project account.
account: EcoGenetics
# Name of species being worked on.
species_name: Stegodyphus lineatus
# Path to sample alignment file (BAM format). Can be a list with multiple entries or a single entry
sample_list:
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f1_121_F/SteLin_f1_121_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f1_126_M/SteLin_f1_126_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f2_122_F/SteLin_f2_122_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f2_127_M/SteLin_f2_127_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f3_123_F/SteLin_f3_123_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f3_128_M/SteLin_f3_128_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f4_124_F/SteLin_f4_124_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f4_129_M/SteLin_f4_129_M_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f5_125_F/SteLin_f5_125_F_filtered.bam
- /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/individual_data/Stegodyphus_lineatus/SteLin_f5_130_M/SteLin_f5_130_M_filtered.bam
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_lineatus/LIN_hifi_hic_scaffolded_trim.fa
# Path to BED formatted file containing repeat regions
repeat_regions_bed: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/X_evolution/data/genomes/reference_genomes/Stegodyphus_lineatus/annotation/SteLin.repeats.bed
# Directory for intermidiary files and various statistics.
working_directory: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/steps
# What type of sequencing has been used on the samples, individual sequencing or pooled sequencing (individual | pooled)
sequencing_type: individual
# Ploidy of sample. If sample is pooled the value should equal the total number chromosome copies
ploidy: 2
# Freebayes is a haplotype-based variant caller. The value of 'bestn' is the max number of best alternative haplotypes to consider when more are available.
# This is very time and memory intensive (don't use a value higher than 3).
bestn: 3
